import type { Metadata } from 'next';
import '@/styles/reset.css';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'URYU MYAO | Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
